name: Publish Package to npmjs
on:
  # release:
  #   types: [published]
  workflow_dispatch:
env:
  EM_VERSION: 1.39.14
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build jq-web
        run: |
          export NODE_OPTIONS='--no-experimental-fetch'
          make
          npm ci
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}